
name: inglebard/rsyslog

on:
  push:
    branches: [ rsyslog ]
  pull_request:
    branches: [ rsyslog ]
  schedule:
    - cron:  '0 20 20 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: rsyslog
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: docker build inglebard/rsyslog
      run: |
        docker build . -t inglebard/rsyslog
    - name: docker push
      run: |
        docker push inglebard/rsyslog
