name: inglebard/stable-diffusion-ui

on:
  push:
    branches: [ stable-diffusion-ui ]
  pull_request:
    branches: [ stable-diffusion-ui ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: stable-diffusion-ui
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: docker build inglebard/stable-diffusion-ui
      run: |
        docker build . -t inglebard/stable-diffusion-ui
    - name: docker push
      run: |
        docker push inglebard/stable-diffusion-ui
