name: inglebard/exim

on:
  push:
    branches: [ exim ]
  pull_request:
    branches: [ exim ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: exim
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build inglebard/exim
      run: |
        docker build . -t inglebard/exim
    - name: docker push
      run: |
        docker push inglebard/exim
