name: inglebard/sendmail

on:
  push:
    branches: [ sendmail ]
  pull_request:
    branches: [ sendmail ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: sendmail
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build inglebard/sendmail
      run: |
        docker build . -t inglebard/sendmail
    - name: docker push
      run: |
        docker push inglebard/sendmail
