name: inglebard/vue-cli

on:
  push:
    branches: [ vue-cli ]
  pull_request:
    branches: [ vue-cli ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: vue-cli
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: docker build inglebard/vue-cli
      run: |
        docker build . -t inglebard/vue-cli
    - name: docker push
      run: |
        docker push inglebard/vue-cli
