name: inglebard/tor-relay

on:
  push:
    branches: [ tor-relay ]
  pull_request:
    branches: [ tor-relay ]
  schedule:
    - cron:  '0 20 20 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: tor-relay
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build inglebard/tor-relay
      run: |
        docker build . -t inglebard/tor-relay
    - name: docker push
      run: |
        docker push inglebard/tor-relay
