name: inglebard/angular-cli

on:
  push:
    branches: [ angular-cli ]
  pull_request:
    branches: [ angular-cli ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: angular-cli
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build inglebard/angular-cli
      run: |
        docker build . -t inglebard/angular-cli
    - name: docker push
      run: |
